source "https://rubygems.org"

gem "rails", "~> 7.1"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"
gem "rack-cors"
gem "image_processing", "~> 1.2"
gem "ruby-vips"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
