source "https://rubygems.org"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"
gem "rack-cors"
gem "rack-attack"
gem "image_processing", "~> 1.2"
gem "ruby-vips"
gem "aws-sdk-s3", require: false
# json 3 retire l'option quirks_mode encore utilisée par ActiveSupport 7.2
gem "json", "~> 2.10"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
end

group :development do
  gem "rubocop-rails-omakase", require: false
end
